import { z } from 'zod';

export const objectIdSchema = z.string().regex(/^[a-f\d]{24}$/i, 'Invalid id');

/** E.164, e.g. +919876543210 */
export const phoneSchema = z
  .string()
  .trim()
  .regex(/^\+[1-9]\d{7,14}$/, 'Phone must be in E.164 format, e.g. +919876543210');

/** Multipart forms send "true"/"false" strings; z.coerce.boolean() would turn "false" into true. */
export const booleanFromString = z.preprocess((v) => {
  if (v === 'true' || v === true || v === '1') return true;
  if (v === 'false' || v === false || v === '0') return false;
  return v;
}, z.boolean());

/** Multipart repeats a field name for arrays; a single value arrives as a plain string. */
export const stringArray = z.preprocess((v) => (typeof v === 'string' ? [v] : v), z.array(z.string()));

export const idParamSchema = z.object({ id: objectIdSchema });

export const paginationSchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(60).default(12),
});

/** Product slugs are generated by slugify(): lowercase alphanumerics and hyphens, ≤ 90 chars incl. suffix. */
export const slugParamSchema = z.object({ slug: z.string().trim().regex(/^[a-z0-9-]{1,90}$/, 'Invalid product slug') });
